Support python 3.13
coal-library/coal pull request #641
Opened 2024-12-30 17:47 UTC by Moisan

* Replace Python 3.12 by Python 3.13 as the default
* Update pixi.lock
* Test Python 3.13 in CI

2024-12-30 17:53 UTC, nim65s requested changes

2024-12-30 17:53 UTC, nim65s commented on .github/workflows/macos-linux-pip.yml
> +        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
This is not ready yet for pip

2024-12-31 00:15 UTC, Moisan commented
I see that `scipy`, which is a transitive dependency through `eigenpy`, started supporting Python 3.13 in [release `4.14.1`](https://github.com/scipy/scipy/releases/tag/v1.14.1) and dropped support for python 3.9 in [release `4.14.0`](https://github.com/scipy/scipy/releases/tag/v1.14.0). Hence, if we want to support Python 3.13, we would need to drop Python 3.9 support.

2024-12-31 09:56 UTC, nim65s commented
no, we can depend on scipy 4.14.1 for python 3.13 and on scipy 4.13 for python 3.9

2025-01-03 09:47 UTC, jorisv requested changes

2025-01-03 09:47 UTC, jorisv commented on pixi.toml
> +[feature.py313.dependencies]
Maybe we can rename this feature into py-latest and the py39 into py-oldest ?

2025-01-03 09:47 UTC, jorisv commented on pixi.toml
> +scipy = ">=1.14.1"
I think you don't need this constraint.
I run without it locally and pixi resolve the good version.

2025-01-03 09:47 UTC, jorisv commented on pixi.toml
> +scipy = "<1.14.0"
Same here, pixi use the 1.13.1 verison without setting this constraint.

2025-01-03 15:09 UTC, jorisv approved these changes

2025-01-05 21:45 UTC, Moisan commented on .github/workflows/macos-linux-pip.yml
> +        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
I'm not sure what you mean. What is missing here?

2025-01-06 08:29 UTC, jorisv commented on .github/workflows/macos-linux-pip.yml
> +        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
I think the pip packages are not publish on python 3.13

2025-01-06 08:35 UTC, jorisv commented
@Moisan I have rebase your branch on devel.

2025-01-08 08:41 UTC, jorisv commented on .github/workflows/macos-linux-pip.yml
> +        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
@nim65s PIP CI is green even in 3.13. Can we close this discussion ?

2025-01-08 10:34 UTC, nim65s commented on .github/workflows/macos-linux-pip.yml
> +        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
yes

2025-01-09 11:04 UTC, jorisv approved these changes

2025-01-09 11:10 UTC, jorisv submitted a review, later dismissed

2025-01-09 11:11 UTC, jorisv approved these changes

2025-01-09 11:15 UTC, nim65s commented on .github/workflows/macos-linux-pip.yml
> +        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
```suggestion
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
```

python 3.8 does not work on github macos arm runners

2025-01-09 11:16 UTC, nim65s commented on .github/workflows/macos-linux-pip.yml
> +        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
Oh, wait, it is already excluded

2025-01-09 11:16 UTC, nim65s approved these changes
lgtm for pip part

2025-01-09 14:14 UTC, merged

2025-01-09 14:14 UTC, jorisv commented
Merged.

@Moisan thank's for the contribution.